-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Aug 22, 2023 at 07:23 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `youtube_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `youtube_channels`
--

CREATE TABLE `youtube_channels` (
  `id` int(11) NOT NULL,
  `profilePicture` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `youtube_channels`
--

INSERT INTO `youtube_channels` (`id`, `profilePicture`, `name`, `description`) VALUES
(1, 'https://yt3.ggpht.com/ytc/AOPolaSbaST1JBNd9phht_n7tFN-VHx0FlvKPHeSDnmu4Q=s240-c-k-c0x00ffffff-no-rj', 'Netflix', 'Hi? Hi. ðŸ‚ \n\nGet Netflix\'s latest trailers and updates here! Netflix is the world\'s leading streaming entertainment service with over 209 million paid memberships in over 190 countries enjoying TV series, documentaries, feature films , and games across a wide variety of genres and languages. Members can watch as much as they want, anytime, anywhere, on any internet-connected screen. Members can play, pause and resume watching at any time.\n'),
(2, 'https://yt3.ggpht.com/ytc/AOPolaQ2iMmw9cWFFjnwa13nBwtZQbl-AqGYkkiTqNaTLg=s240-c-k-c0x00ffffff-no-rj', 'Fireship', 'High-intensity âš¡ code tutorials and tech news to help you ship your app faster. New videos every week covering the topics every programmer should know. \n\nThe original home of #100SecondsOfCode #TheCodeReport and #CodeThisNotThat. Created by Jeff Delaney. \n\nBuilding an app? Get project support, advanced full courses, and more at https://fireship.io');

-- --------------------------------------------------------

--
-- Table structure for table `youtube_channel_videos`
--

CREATE TABLE `youtube_channel_videos` (
  `id` int(11) NOT NULL,
  `videoLink` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `thumbnail` varchar(255) NOT NULL,
  `channel` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `youtube_channel_videos`
--

INSERT INTO `youtube_channel_videos` (`id`, `videoLink`, `title`, `description`, `thumbnail`, `channel`) VALUES
(1, 'https://www.youtube.com/watch?v=KS1cNkZ9o1U', 'Reptile | Benicio Del Toro &amp; Justin Timberlake | Official Trailer | Netflix', 'A mysterious murder. A hardened detective. A truth more dangerous than they could have ever imagined. Benicio Del Toro, Justin ...', 'https://i.ytimg.com/vi/KS1cNkZ9o1U/mqdefault.jpg', 'Netflix'),
(2, 'https://www.youtube.com/watch?v=ZF06TZta1l0', 'ONE PIECE | Inside the Story | Netflix', 'Go behind the scenes of Netflix\'s live action One Piece. SUBSCRIBE: http://bit.ly/29qBUt7 About Netflix: Netflix is one of the ...', 'https://i.ytimg.com/vi/ZF06TZta1l0/mqdefault.jpg', 'Netflix'),
(3, 'https://www.youtube.com/watch?v=-bXE3aw6P9g', 'The Club: Season 2 | Date Announcement | Netflix', 'With her husband gone, RaÅŸel raises her daughter at Club Istanbul with the help of her mother, but their relationships are tested ...', 'https://i.ytimg.com/vi/-bXE3aw6P9g/mqdefault.jpg', 'Netflix'),
(4, 'https://www.youtube.com/watch?v=0-fVANWP2_g', 'Love At First Sight: Official First Look | Netflix', 'After missing her flight from New York to London, Hadley (Haley Lu Richardson) meets Oliver (Ben Hardy) in a chance encounter ...', 'https://i.ytimg.com/vi/0-fVANWP2_g/mqdefault.jpg', 'Netflix'),
(5, 'https://www.youtube.com/watch?v=nqExE6OguzI', 'UNTOLD: Swamp Kings | Florida Gators | Official Teaser | Netflix', 'After a blazing run in the 1990s under Coach Steve Spurrier, the University of Florida\'s winning streak had dried up by 2005.', 'https://i.ytimg.com/vi/nqExE6OguzI/mqdefault.jpg', 'Netflix'),
(6, 'https://www.youtube.com/watch?v=_1wvmUXLAlA', 'Inside the Worldâ€™s Toughest Prisons: Season 7 | Official Trailer | Netflix', 'Journalist and former inmate Raphael Rowe experiences life inside prisons in Finland, the Czech Republic, Indonesia and the ...', 'https://i.ytimg.com/vi/_1wvmUXLAlA/mqdefault.jpg', 'Netflix'),
(7, 'https://www.youtube.com/watch?v=drF6rJ9wRxY', 'it&#39;s been 5 years since the world saw this scene for the first time ðŸ’– #toalltheboysivelovedbefore', 'shorts #netflix SUBSCRIBE: http://bit.ly/29qBUt7 About Netflix: Netflix is one of the world\'s leading entertainment services with over ...', 'https://i.ytimg.com/vi/drF6rJ9wRxY/mqdefault.jpg', 'Netflix'),
(8, 'https://www.youtube.com/watch?v=BWmyVK09CZ4', 'Surviving Summer Season 2 | Official Trailer | Netflix', 'A new rival drops in as Summer trains with her friends for the national surfing competition, challenging her on the waves â€” and for ...', 'https://i.ytimg.com/vi/BWmyVK09CZ4/mqdefault.jpg', 'Netflix'),
(9, 'https://www.youtube.com/watch?v=_4YP-lD6R_M', 'Disenchantment: The Final Season | Official Trailer | Netflix', 'CONTROL YOUR EMOTIONS, CONTROL THE MAGIC. Bean\'s final, epic adventure comes to a shocking conclusion. Premieres ...', 'https://i.ytimg.com/vi/_4YP-lD6R_M/mqdefault.jpg', 'Netflix'),
(10, 'https://www.youtube.com/watch?v=16EoQqRQwJM', 'Ehrengard: The Art of Seduction | Official Trailer | Netflix', 'Even a good player will someday be played. It\'s called karma. See Mikkel Boe FÃ¸lsgaard and Sidse Babett Knudsen in ...', 'https://i.ytimg.com/vi/16EoQqRQwJM/mqdefault.jpg', 'Netflix'),
(11, 'https://www.youtube.com/watch?v=it-8MIm29bI', 'Live to 100: Secrets of the Blue Zones | Official Trailer | Netflix', 'Travel around the world with author Dan Buettner to discover five unique communities where people live extraordinarily long and ...', 'https://i.ytimg.com/vi/it-8MIm29bI/mqdefault.jpg', 'Netflix'),
(12, 'https://www.youtube.com/watch?v=BeJuxMYhmEc', 'Heart of Invictus | Official Trailer | Netflix', 'Follow a group of competitors, from around the globe, all service members who have experienced life-changing injuries or ...', 'https://i.ytimg.com/vi/BeJuxMYhmEc/mqdefault.jpg', 'Netflix'),
(13, 'https://www.youtube.com/watch?v=ompoD7V42DM', 'Scott Pilgrim | Official Teaser | Netflix', 'Here\'s a first look at the Scott Pilgrim Anime coming to Netflix November 17th add it to your list today. SUBSCRIBE: ...', 'https://i.ytimg.com/vi/ompoD7V42DM/mqdefault.jpg', 'Netflix'),
(14, 'https://www.youtube.com/watch?v=ijQrpzYp8t4', 'Tahir&#39;s House | Official Trailer | Netflix', 'A family of amateur entrepreneurs must come together to convert their failing fish shop into a thriving business, but branching out ...', 'https://i.ytimg.com/vi/ijQrpzYp8t4/mqdefault.jpg', 'Netflix'),
(15, 'https://www.youtube.com/watch?v=8ChzVBC2-10', 'Cut the Rope Daily | Om Nom Trailer | Netflix', 'Solve one new logic puzzle every day to keep your streak alive. Cut ropes and pop balloons to feed cute green monster Om Nom, ...', 'https://i.ytimg.com/vi/8ChzVBC2-10/mqdefault.jpg', 'Netflix'),
(16, 'https://www.youtube.com/watch?v=zU6GbM5c9aE', 'Maestro | Official Teaser | Netflix', 'Maestro is a towering and fearless love story chronicling the lifelong relationship between cultural icon Leonard Bernstein and ...', 'https://i.ytimg.com/vi/zU6GbM5c9aE/mqdefault.jpg', 'Netflix'),
(17, 'https://www.youtube.com/watch?v=uLlKhqNqJBU', 'How Canelo Ãlvarez Gets Inspired to Fight | Nobody Hits Like Netflix', 'With his big match around the corner, here\'s how champion boxer Canelo Ãlvarez stays inspired to go hard in the ring. Don\'t miss ...', 'https://i.ytimg.com/vi/uLlKhqNqJBU/mqdefault.jpg', 'Netflix'),
(18, 'https://www.youtube.com/watch?v=Wd3970ffrxQ', 'I Don&#39;t Expect Anyone to Believe Me | Official Teaser | Netflix', 'Juan Pablo Villalobos travels with his girlfriend Valentina to study a PhD in Literature in Barcelona. But before he leaves Mexico, ...', 'https://i.ytimg.com/vi/Wd3970ffrxQ/mqdefault.jpg', 'Netflix'),
(19, 'https://www.youtube.com/watch?v=aLGc7Edu3Cg', 'Scouts Honor: The Secret Files of the Boy Scouts of America | Official Trailer | Netflix', 'Survivors, whistleblowers and experts recount the Boy Scouts of America\'s decadeslong cover-up of sexual abuse cases and its ...', 'https://i.ytimg.com/vi/aLGc7Edu3Cg/mqdefault.jpg', 'Netflix'),
(20, 'https://www.youtube.com/watch?v=BYLYZ7OsymE', 'Top Boy: Season 3 | Official Trailer | Netflix', 'No. Loose. Ends ... The Final Chapter of TOP BOY available September 7. Only on Netflix SUBSCRIBE: http://bit.ly/29qBUt7 About ...', 'https://i.ytimg.com/vi/BYLYZ7OsymE/mqdefault.jpg', 'Netflix'),
(21, 'https://www.youtube.com/watch?v=kHDjc8GIg8A', '#AliaBhatt tells the story when she met #GalGadot', 'Go behind the scenes of Heart Of Stone with star #AliaBhatt. #shorts #netflix SUBSCRIBE: http://bit.ly/29qBUt7 About Netflix: ...', 'https://i.ytimg.com/vi/kHDjc8GIg8A/mqdefault.jpg', 'Netflix'),
(22, 'https://www.youtube.com/watch?v=XuDwndGaCFo', 'Heart of Stone | Gal Gadot | Official Trailer | Netflix', 'Gal Gadot, Jamie Dornan, Alia Bhatt, Matthias SchweighÃ¶fer in HEART OF STONE. Only on Netflix August 11. Gal Gadot is Agent ...', 'https://i.ytimg.com/vi/XuDwndGaCFo/mqdefault.jpg', 'Netflix'),
(23, 'https://www.youtube.com/watch?v=m9EhNRdMPJc', 'Lindsay Lohan Reads Twelve Days of Christmas | Netflix', 'On the first day of Christmas, Lindsay Lohan gave to me... an âœ¨iconicâœ¨ reading of \"Twelve Days of Christmas\" SUBSCRIBE: ...', 'https://i.ytimg.com/vi/m9EhNRdMPJc/mqdefault.jpg', 'Netflix'),
(24, 'https://www.youtube.com/watch?v=-QCFifHyXNM', 'Money Heist: Korea - Joint Economic Area Part 2 | Official Trailer | Netflix', 'When everything falls apart, The real plan starts. Perfect, down to the very last detail Intense, more than ever before Money Heist: ...', 'https://i.ytimg.com/vi/-QCFifHyXNM/mqdefault.jpg', 'Netflix'),
(25, 'https://www.youtube.com/watch?v=Ke-Qermu9Ps', 'Antoni, Jacques &amp; Fortune play Nailed It! Baking Bash mobile game | Netflix', 'Don\'t forget to check out - Antoni Porowski hosting Easy-Bake Battle, which premieres on Netflix on October 12 and Fortune ...', 'https://i.ytimg.com/vi/Ke-Qermu9Ps/mqdefault.jpg', 'Netflix'),
(26, 'https://www.youtube.com/watch?v=keeCl9vYVrE', 'Tudum: A Netflix Global Fan Event | Exclusive Clip | September 21 | Netflix', 'Check out a sneak peek at Tudum: A Netflix Global Fan Event, from Reese Witherspoon and Ashton Kutcher in the upcoming film, ...', 'https://i.ytimg.com/vi/keeCl9vYVrE/mqdefault.jpg', 'Netflix'),
(27, 'https://www.youtube.com/watch?v=iXdw5wYI4cY', 'The Next 365 Days | Official Trailer | Netflix', 'Laura and Massimo\'s relationship hangs in the balance as they try to overcome trust issues while a tenacious Nacho works to ...', 'https://i.ytimg.com/vi/iXdw5wYI4cY/mqdefault.jpg', 'Netflix'),
(28, 'https://www.youtube.com/watch?v=u1pUFjpdH5o', 'Never Have I Ever: ï»¿Everything We Can Tell You About Season 3 | Netflix', 'Devi (Maitreyi Ramakrishnan) and all your favs from Sherman Oaks High are back! Here\'s everything we can tell you about Never ...', 'https://i.ytimg.com/vi/u1pUFjpdH5o/mqdefault.jpg', 'Netflix'),
(29, 'https://www.youtube.com/watch?v=_kRab62q54M', 'Love in the Villa | Official Trailer | Netflix', 'A young woman (Kat Graham) takes a trip to romantic Verona, Italy, after a break up, only to find that the villa she reserved was ...', 'https://i.ytimg.com/vi/_kRab62q54M/mqdefault.jpg', 'Netflix'),
(30, 'https://www.youtube.com/watch?v=GeKMXJuiDaA', 'Stay on Board: The Leo Baker Story | Official Trailer | Netflix', 'From Netflix, Pulse Films, a division of VICE Media Group, and Flower Films comes a raw and immersive feature film that follows ...', 'https://i.ytimg.com/vi/GeKMXJuiDaA/mqdefault.jpg', 'Netflix'),
(31, 'https://www.youtube.com/watch?v=0JqCTYEsDdw', 'Heartbreak High | Date Announcement | Netflix', 'It\'s their world, live in it. Heartbreak High premieres on September 14th. Only on Netflix. SUBSCRIBE: http://bit.ly/29qBUt7 About ...', 'https://i.ytimg.com/vi/0JqCTYEsDdw/mqdefault.jpg', 'Netflix'),
(32, 'https://www.youtube.com/watch?v=1Qcm1UMjjoU', 'Partner Track | Official Trailer | Netflix', 'Being on the partner track is how you find out who you really are. Meet your biggest competition, Ingrid Yun. Based on the ...', 'https://i.ytimg.com/vi/1Qcm1UMjjoU/mqdefault.jpg', 'Netflix'),
(33, 'https://www.youtube.com/watch?v=a2Oual5EjcU', 'I Just Killed My Dad | Official Trailer | Netflix', 'Anthony Templet shot his father and never denied it. But why he did is a complex question with profound implications that go far ...', 'https://i.ytimg.com/vi/a2Oual5EjcU/mqdefault.jpg', 'Netflix'),
(34, 'https://www.youtube.com/watch?v=W3M2_pV-SGY', 'Untold: The Rise and Fall of AND1 | Official Trailer | Netflix', 'Born out of the playgrounds of New York City, the â€œAnd 1 Mixtape Tourâ€ took streetball to the masses, challenging convention and ...', 'https://i.ytimg.com/vi/W3M2_pV-SGY/mqdefault.jpg', 'Netflix'),
(35, 'https://www.youtube.com/watch?v=6DiOR_5-fkc', 'Fate: The Winx Saga: Season 2 | Date Announcement | Netflix', 'Magic and mystery await at Alfea.âœ¨ See you on September 16. Check out what\'s in store for Season 2 of Fate: The Winx Saga as ...', 'https://i.ytimg.com/vi/6DiOR_5-fkc/mqdefault.jpg', 'Netflix'),
(36, 'https://www.youtube.com/watch?v=5Ux_ipIsNyo', 'Running with the Devil: The Wild World of John McAfee | Official Trailer | Netflix', 'Through raw, revealing footage and interviews with fugitive tech pioneer John McAfee, this documentary uncovers new layers of ...', 'https://i.ytimg.com/vi/5Ux_ipIsNyo/mqdefault.jpg', 'Netflix'),
(37, 'https://www.youtube.com/watch?v=0Fyja48qK2g', 'The Sandman | The World of The Endless | Netflix', 'Visionary author Neil Gaiman explains the story behind The Sandman and the titular character\'s god-like siblings, The Endless.', 'https://i.ytimg.com/vi/0Fyja48qK2g/mqdefault.jpg', 'Netflix'),
(38, 'https://www.youtube.com/watch?v=Mmq_NVwLN_g', 'ME TIME | Official Trailer | Netflix', 'When a stay-at-home dad finds himself with some â€œme timeâ€ for the first time in years while his wife and kids are away, ...', 'https://i.ytimg.com/vi/Mmq_NVwLN_g/mqdefault.jpg', 'Netflix'),
(39, 'https://www.youtube.com/watch?v=jkb4F7OuB0A', 'Into the Breach | Official Game Trailer | Netflix', 'Civilization is in peril, and it\'s up to you to defend it. Lead a team to save the world from alien threats in this turn-based strategy ...', 'https://i.ytimg.com/vi/jkb4F7OuB0A/mqdefault.jpg', 'Netflix'),
(40, 'https://www.youtube.com/watch?v=sTj-jHfhdzo', 'Untold: The Girlfriend Who Didn&#39;t Exist | Official Trailer | Netflix', 'Born into a Hawaiian paradise, All-American football standout Manti Te\'o leads a simple life summed up in just three words: faith, ...', 'https://i.ytimg.com/vi/sTj-jHfhdzo/mqdefault.jpg', 'Netflix'),
(41, 'https://www.youtube.com/watch?v=jdy7iv5QjWU', 'Tourists React to Prank: Real Life Sea Monster Attack! | Netflix', 'TheSeaBeast #Prank #KarlUrban See what happens when we bring big monsters to the beach, then stay home and watch The ...', 'https://i.ytimg.com/vi/jdy7iv5QjWU/mqdefault.jpg', 'Netflix'),
(42, 'https://www.youtube.com/watch?v=JYV57JDgDdU', '13: The Musical | Official Trailer | Netflix', 'After his parents\' divorce, Evan Goldman (Eli Golden) moves from NYC to small-town Indiana. As his 13th birthday nears, he must ...', 'https://i.ytimg.com/vi/JYV57JDgDdU/mqdefault.jpg', 'Netflix'),
(43, 'https://www.youtube.com/watch?v=lInnMkPbEng', 'Street Food: USA | Official Trailer | Netflix', 'Get a taste of the most beloved bites on American streets and, along the way, discover the heart, soul and wildly diverse real ...', 'https://i.ytimg.com/vi/lInnMkPbEng/mqdefault.jpg', 'Netflix'),
(44, 'https://www.youtube.com/watch?v=WTLgg8oRSBE', 'Purple Hearts | Official Trailer | Netflix', 'In spite of their many differences, Cassie (Sofia Carson), a struggling singer-songwriter, and Luke (Nicholas Galitzine), a troubled ...', 'https://i.ytimg.com/vi/WTLgg8oRSBE/mqdefault.jpg', 'Netflix'),
(45, 'https://www.youtube.com/watch?v=PfZ3KaX5CiA', 'Virgin River: Season 4 | Official Trailer | Netflix', 'Despite not knowing whether her baby belongs to her deceased husband, Mark or Jack, Mel begins Season Four with a sense of ...', 'https://i.ytimg.com/vi/PfZ3KaX5CiA/mqdefault.jpg', 'Netflix'),
(46, 'https://www.youtube.com/watch?v=d6OrdQJAvnM', 'The Sea Beast | Exclusive Monster Battle Clip | Netflix', 'Jacob and Maisie\'s hands are tied when they have to escape from inside a ferocious beast, The Red Bluster. There is only one ...', 'https://i.ytimg.com/vi/d6OrdQJAvnM/mqdefault.jpg', 'Netflix'),
(47, 'https://www.youtube.com/watch?v=ZiZcFFTPxH4', 'Evolving Resident Evil | Netflix', 'An inside look at Netflix\'s TV adaptation of the Resident Evil franchise. SUBSCRIBE: http://bit.ly/29qBUt7 About Netflix: Netflix is ...', 'https://i.ytimg.com/vi/ZiZcFFTPxH4/mqdefault.jpg', 'Netflix'),
(48, 'https://www.youtube.com/watch?v=xqqTL91J1lo', 'Wedding Season | Official Trailer | Netflix', 'Pressured by their parents to find spouses, Asha (Pallavi Sharda) and Ravi (Suraj Sharma) pretend to date in order to survive a ...', 'https://i.ytimg.com/vi/xqqTL91J1lo/mqdefault.jpg', 'Netflix'),
(49, 'https://www.youtube.com/watch?v=ec-EIWNGAZc', 'Watch This Before Stranger Things 4 Volume 2 | Netflix', 'The clock is ticking on the premiere of Stranger Things 4 Volume 2. Watch this recap before venturing back into the Upside Down ...', 'https://i.ytimg.com/vi/ec-EIWNGAZc/mqdefault.jpg', 'Netflix'),
(50, 'https://www.youtube.com/watch?v=pfhCEXLnQh8', 'Keep Breathing | Official Trailer | Netflix', 'When a small plane crashes in the middle of the Canadian wilderness, a lone survivor must battle the elements â€” and her ...', 'https://i.ytimg.com/vi/pfhCEXLnQh8/mqdefault.jpg', 'Netflix'),
(51, 'https://www.youtube.com/watch?v=MYy7oGQiSqI', 'Kung Fu Panda: The Dragon Knight ðŸ»â€â„ï¸ðŸ‰ Official Trailer | Netflix', 'When a mysterious pair of weasels set their sights on a collection of four powerful weapons, Po must leave his home to embark on ...', 'https://i.ytimg.com/vi/MYy7oGQiSqI/mqdefault.jpg', 'Netflix'),
(52, 'https://www.youtube.com/watch?v=xltjtd4Tx1A', 'How To Build a Sex Room | Official Trailer | Netflix', 'Couples looking for more spice in the bedroom hire luxury interior designer Melanie Rose to create stylish spaces where they can ...', 'https://i.ytimg.com/vi/xltjtd4Tx1A/mqdefault.jpg', 'Netflix'),
(53, 'https://www.youtube.com/watch?v=29i4ZpCxeJA', 'D.B. Cooper: Where Are You?! | Official Trailer | Netflix', 'In 1971, a skyjacker parachutes off a plane with a bag of stolen cash â€” and gets away with it. Decades later, his identity remains a ...', 'https://i.ytimg.com/vi/29i4ZpCxeJA/mqdefault.jpg', 'Netflix'),
(54, 'https://www.youtube.com/watch?v=X8LRb4jfZ9g', 'How to Change Your Mind | Official Trailer | Netflix', 'Academy Award-winning filmmaker Alex Gibney and New York Times best-selling author Michael Pollan present this ...', 'https://i.ytimg.com/vi/X8LRb4jfZ9g/mqdefault.jpg', 'Netflix'),
(55, 'https://www.youtube.com/watch?v=HY7GgQhY51M', 'Iron Chef: Quest for an Iron Legend | Inside The New Kitchen Stadium | Netflix', 'Iron Chef host Alton Brown and Kristen Kish give a first look behind the scenes of the new Kitchen Stadium. Iron Chef is back!', 'https://i.ytimg.com/vi/HY7GgQhY51M/mqdefault.jpg', 'Netflix'),
(56, 'https://www.youtube.com/watch?v=MX6wAGuIMCg', 'HELLO, GOODBYE, AND EVERYTHING IN BETWEEN | Official Trailer | Netflix', 'After making a pact to break up before college, Clare (Talia Ryder) and Aidan (Jordan Fisher) spend their last evening as a couple ...', 'https://i.ytimg.com/vi/MX6wAGuIMCg/mqdefault.jpg', 'Netflix'),
(57, 'https://www.youtube.com/watch?v=kB3bN22c60o', 'Love, Death + Robots | Inside the Animation: Bad Travelling | Netflix', 'David Fincher, director of Bad Travelling featured in Love, Death + Robots Vol. 3 discusses how he approached directing his first ...', 'https://i.ytimg.com/vi/kB3bN22c60o/mqdefault.jpg', 'Netflix'),
(58, 'https://www.youtube.com/watch?v=EzKASl2T9d0', 'Roald Dahlâ€™s Matilda the Musical | Official Teaser | Netflix', 'Meet the exception to the rules. Coming soon. SUBSCRIBE: http://bit.ly/29qBUt7 About Netflix: Netflix is the world\'s leading ...', 'https://i.ytimg.com/vi/EzKASl2T9d0/mqdefault.jpg', 'Netflix'),
(59, 'https://www.youtube.com/watch?v=Fz7HmgPJQak', 'Persuasion starring Dakota Johnson | Official Trailer | Netflix', 'Living with her snobby family on the brink of bankruptcy, Anne Elliot is an unconforming woman with modern sensibilities.', 'https://i.ytimg.com/vi/Fz7HmgPJQak/mqdefault.jpg', 'Netflix'),
(60, 'https://www.youtube.com/watch?v=0hgZPvMU7So', 'The Future Of | Official Trailer | Netflix', 'What if we could look into the future to see how every aspect of our daily lives â€“ from raising pets and house plants to what we eat ...', 'https://i.ytimg.com/vi/0hgZPvMU7So/mqdefault.jpg', 'Netflix'),
(61, 'https://www.youtube.com/watch?v=JF_QYFb8vc4', 'GEEKED WEEK - Day 5 | Games Showcase, The Cuphead Show! Table Read &amp; More | Netflix', 'It\'s GEEKED WEEK! Friday, June 10th is GAMES DAY, which means you\'re going to get the latest news, trailers, reveals and ...', 'https://i.ytimg.com/vi/JF_QYFb8vc4/mqdefault.jpg', 'Netflix'),
(62, 'https://www.youtube.com/watch?v=-_sLzHGRVCM', 'THE CUPHEAD SHOW! New Episodes | Official Teaser | Netflix', 'Double down with new episodes of THE CUPHEAD SHOW, coming soon to Netflix. Based on the award-winning video game, ...', 'https://i.ytimg.com/vi/-_sLzHGRVCM/mqdefault.jpg', 'Netflix'),
(63, 'https://www.youtube.com/watch?v=rK6g5mSxj0w', 'Hustle | NBA Stars on How Adam Sandler and LeBron James Bring Authenticity to Hustle | Netflix', 'Hear from NBA stars as they talk about making Adam Sandler\'s new movie Hustle. SUBSCRIBE: http://bit.ly/29qBUt7 About Netflix: ...', 'https://i.ytimg.com/vi/rK6g5mSxj0w/mqdefault.jpg', 'Netflix'),
(64, 'https://www.youtube.com/watch?v=fXkYqdJIpvw', 'GEEKED WEEK - Day 4 | Stranger Things Day | Netflix', 'It\'s GEEKED WEEK! Thursday, June 9th is STRANGER THINGS DAY -- yes, a full day dedicated to the Upside Down! Today\'s ...', 'https://i.ytimg.com/vi/fXkYqdJIpvw/mqdefault.jpg', 'Netflix'),
(65, 'https://www.youtube.com/watch?v=JeUuk-g_Qws', 'Love, Death + Robots | Inside the Animation: Jibaro | Netflix', 'Director Alberto Mielgo gives a glimpse inside the animation of Jibaro featured in Love, Death + Robots Vol. 3. SUBSCRIBE: ...', 'https://i.ytimg.com/vi/JeUuk-g_Qws/mqdefault.jpg', 'Netflix'),
(66, 'https://www.youtube.com/watch?v=8ajQmVRn_Ts', 'Arcane: Bridging the Rift | Official Clip | Netflix', 'Arcane co-creator Christian Linke discusses the series\' inception and the partnership with animation studio, Fortiche, that brought ...', 'https://i.ytimg.com/vi/8ajQmVRn_Ts/mqdefault.jpg', 'Netflix'),
(67, 'https://www.youtube.com/watch?v=P-E-IGQCsPo', 'The Sea Beast | Official Trailer | Netflix', 'This monstrous adventure attacks Netflix July 8. Set a reminder: https://netflix.com/theseabeast From Academy Award winning ...', 'https://i.ytimg.com/vi/P-E-IGQCsPo/mqdefault.jpg', 'Netflix'),
(68, 'https://www.youtube.com/watch?v=cWJTB6FPVaA', 'The Sandman | Date Announcement | Netflix', 'There is another world that waits for all of us when we close our eyes and sleep â€” a place called the Dreaming, where The ...', 'https://i.ytimg.com/vi/cWJTB6FPVaA/mqdefault.jpg', 'Netflix'),
(69, 'https://www.youtube.com/watch?v=Y_zpkX3Z3hk', 'One Piece: Set Sneak Peek | First Look | Netflix Geeked Week', 'Get a first look at the sets of One Piece. Actor IÃ±aki Godoy and showrunners Steven Maeda and Matt Owens introduce a behind ...', 'https://i.ytimg.com/vi/Y_zpkX3Z3hk/mqdefault.jpg', 'Netflix'),
(70, 'https://www.youtube.com/watch?v=eR6OSt_21Sg', 'GEEKED WEEK - Day 1 | Series Showcase, The Sandman &amp; The Umbrella Academy | Netflix', 'It\'s GEEKED WEEK! Monday, June 6th is SERIES DAY, which means you\'re going to get the latest news, trailers, reveals and cast ...', 'https://i.ytimg.com/vi/eR6OSt_21Sg/mqdefault.jpg', 'Netflix'),
(71, 'https://www.youtube.com/watch?v=7fdEqs3fiFw', 'Pirate Gold of Adak Island | Official Trailer | Netflix', 'Over the past one hundred years, caches of gold coins from the nineteenth century have been found buried on the remote and ...', 'https://i.ytimg.com/vi/7fdEqs3fiFw/mqdefault.jpg', 'Netflix'),
(72, 'https://www.youtube.com/watch?v=ZpeODtrVgUQ', 'First Kill | Inside the Story | Netflix', 'The cast of First Kill and showrunner Felicia D. Henderson take you inside Juliette and Calliope\'s forbidden love story. You never ...', 'https://i.ytimg.com/vi/ZpeODtrVgUQ/mqdefault.jpg', 'Netflix'),
(73, 'https://www.youtube.com/watch?v=9RJf3l8QXWs', 'Iron Chef: Quest for an Iron Legend | Official Trailer | Netflix', 'Who will master the masters? Challenger chefs take on the Iron Chefs in a series of culinary battles for the chance to be crowned ...', 'https://i.ytimg.com/vi/9RJf3l8QXWs/mqdefault.jpg', 'Netflix'),
(74, 'https://www.youtube.com/watch?v=VY_vTWAdffA', 'As The Crow Flies | Official Trailer | Netflix', 'The bird is the hunter, the lion is the prey. #AsTheCrowFlies only on Netflix, June 3rd. SUBSCRIBE: http://bit.ly/29qBUt7 About ...', 'https://i.ytimg.com/vi/VY_vTWAdffA/mqdefault.jpg', 'Netflix'),
(75, 'https://www.youtube.com/watch?v=BmllggGO4pM', 'THE GRAY MAN | Official Trailer | Netflix', 'Ryan Gosling is THE GRAY MAN and Chris Evans is his psychopathic adversary in the Netflix/AGBO spy thriller directed by ...', 'https://i.ytimg.com/vi/BmllggGO4pM/mqdefault.jpg', 'Netflix'),
(76, 'https://www.youtube.com/watch?v=Nrony8-xhHM', 'Snowflake Mountain | Official Trailer | Netflix', 'Welcome to Snowflake Mountain. A place where ragtag stuck at home snowflakes with zero life skills have to step up to the plate.', 'https://i.ytimg.com/vi/Nrony8-xhHM/mqdefault.jpg', 'Netflix'),
(77, 'https://www.youtube.com/watch?v=XVBvTErpdq4', 'You Don&#39;t Know Me | Official Trailer | Netflix', 'A young unnamed defendant stands in the dock accused of murder. He has fired his barrister and is now representing himself.', 'https://i.ytimg.com/vi/XVBvTErpdq4/mqdefault.jpg', 'Netflix'),
(78, 'https://www.youtube.com/watch?v=-voLo_TIWf4', 'Halftime | Jennifer Lopez | Official Trailer | Netflix', 'HALFTIME offers an intimate peek behind the curtain revealing the grit and determination that makes Jennifer Lopez. The film ...', 'https://i.ytimg.com/vi/-voLo_TIWf4/mqdefault.jpg', 'Netflix'),
(79, 'https://www.youtube.com/watch?v=BfsNfFoA0J0', 'Spiderhead | Chris Hemsworth | Official Trailer | Netflix', 'Two inmates (Miles Teller & Jurnee Smollett) form a connection while grappling with their pasts in a state-of-the-art penitentiary ...', 'https://i.ytimg.com/vi/BfsNfFoA0J0/mqdefault.jpg', 'Netflix'),
(80, 'https://www.youtube.com/watch?v=4VuzxlHqTAs', 'Trees of Peace | Official Trailer | Netflix', 'Four women from different backgrounds forge an unbreakable sisterhood while trapped and in hiding during the genocide in ...', 'https://i.ytimg.com/vi/4VuzxlHqTAs/mqdefault.jpg', 'Netflix'),
(81, 'https://www.youtube.com/watch?v=Tx6onHvOqwA', 'Resident Evil | Official Teaser #2 | Netflix', 'How could so much Joy create so much pain? Resident Evil comes exclusively to Netflix, July 14th. SUBSCRIBE: ...', 'https://i.ytimg.com/vi/Tx6onHvOqwA/mqdefault.jpg', 'Netflix'),
(82, 'https://www.youtube.com/watch?v=D4wJK4C_nZY', 'First Kill | Official Trailer | Netflix', 'You never forget your first. Teenage vampire Juliette sets her sights on a new girl in town Calliope for her first kill. But much to ...', 'https://i.ytimg.com/vi/D4wJK4C_nZY/mqdefault.jpg', 'Netflix'),
(83, 'https://www.youtube.com/watch?v=nM4iy0reaCA', 'Hustle starring Adam Sandler | Official Trailer | Netflix', 'After discovering a once-in-a-lifetime player with a rocky past abroad, a down on his luck basketball scout (Adam Sandler) takes it ...', 'https://i.ytimg.com/vi/nM4iy0reaCA/mqdefault.jpg', 'Netflix'),
(84, 'https://www.youtube.com/watch?v=wpC02rGi8d0', 'A Farewell to Ozark | Netflix', 'Jason Bateman, Laura Linney and other cast members open up about the show\'s characters and creators, plus what they\'ll miss ...', 'https://i.ytimg.com/vi/wpC02rGi8d0/mqdefault.jpg', 'Netflix'),
(85, 'https://www.youtube.com/watch?v=Wrmx6gc0a8I', 'Cobra Kai Season 5 | Date Announcement | Netflix', 'Following the shocking results of the All Valley Tournament, Terry Silver is expanding the Cobra Kai empire and trying to make his ...', 'https://i.ytimg.com/vi/Wrmx6gc0a8I/mqdefault.jpg', 'Netflix'),
(86, 'https://www.youtube.com/watch?v=86TrUPszc9Y', 'Love on the Spectrum U.S. | Official Trailer | Netflix', 'This insightful and warm hearted docuseries follows autistic people as they navigate the world of dating and relationships.', 'https://i.ytimg.com/vi/86TrUPszc9Y/mqdefault.jpg', 'Netflix'),
(87, 'https://www.youtube.com/watch?v=OQSoII4Bj1o', 'INTERCEPTOR | Official Trailer | Netflix', 'Meet the world\'s last defense. One Army captain must use her years of tactical training and military expertise when a simultaneous ...', 'https://i.ytimg.com/vi/OQSoII4Bj1o/mqdefault.jpg', 'Netflix'),
(88, 'https://www.youtube.com/watch?v=zeUq5Duxz1E', 'The G Word with Adam Conover | Official Trailer | Netflix', 'The G Word with Adam Conover is a hybrid comedy-documentary series that pulls back the curtain on the surprising ways the US ...', 'https://i.ytimg.com/vi/zeUq5Duxz1E/mqdefault.jpg', 'Netflix'),
(89, 'https://www.youtube.com/watch?v=U34E6geXBc8', 'Grace and Frankie | A Farewell to 7 Seasons with Jane Fonda and Lily Tomlin | Netflix', 'Jane Fonda, and Lily Tomlin and showrunners Marta Kauffman, and Howard Morris take us on a fun trip down memory lane of the ...', 'https://i.ytimg.com/vi/U34E6geXBc8/mqdefault.jpg', 'Netflix'),
(90, 'https://www.youtube.com/watch?v=AQStrXOSsnY', 'Ozark: Season 4 | Part 1 Recap | Netflix', 'Catch up on the beginning of the end. Ozark concludes, April 29. SUBSCRIBE: http://bit.ly/29qBUt7 About Netflix: Netflix is the ...', 'https://i.ytimg.com/vi/AQStrXOSsnY/mqdefault.jpg', 'Netflix'),
(91, 'https://www.youtube.com/watch?v=WR21TH-6LfY', 'A Perfect Pairing starring Victoria Justice &amp; Adam Demos | Official Trailer | Netflix', 'To land a major client, a hard-driving LA wine-company exec (Victoria Justice) travels to an Australian sheep station, where she ...', 'https://i.ytimg.com/vi/WR21TH-6LfY/mqdefault.jpg', 'Netflix'),
(92, 'https://www.youtube.com/watch?v=nAOIH8HRdDo', 'Meltdown: Three Mile Island | Official Trailer | Netflix', 'This gripping four-part documentary series tackles the near catastrophe at Three Mile Island nuclear power plant in Pennsylvania ...', 'https://i.ytimg.com/vi/nAOIH8HRdDo/mqdefault.jpg', 'Netflix'),
(93, 'https://www.youtube.com/watch?v=WnKmbFhENUg', 'Pacific Rim: The Black Season 1 | Official Recap | Netflix', 'Piloting Atlas Destroyer with Mei and Boy in tow, Hayley and Taylor continue their journey to Sydney, but first, they must get past a ...', 'https://i.ytimg.com/vi/WnKmbFhENUg/mqdefault.jpg', 'Netflix'),
(94, 'https://www.youtube.com/watch?v=phQxK5u8IEs', 'Our Father | Official Trailer | Netflix', 'A top fertility doctor had a sickening secret: he was using his own sperm. Decades later, his â€œchildrenâ€ band together to pursue ...', 'https://i.ytimg.com/vi/phQxK5u8IEs/mqdefault.jpg', 'Netflix'),
(95, 'https://www.youtube.com/watch?v=2kaItzgRzr8', 'Grace and Frankie: Season 7B | Official Trailer | Netflix', 'For 7 years, two unlikely friends made us laugh, made us cry, and made us question what it means to act your age. The final ...', 'https://i.ytimg.com/vi/2kaItzgRzr8/mqdefault.jpg', 'Netflix'),
(96, 'https://www.youtube.com/watch?v=lzCoH0qXHvQ', 'Ozark: Season 4 Part 2 | Saying Goodbye to the Byrde House | Netflix', 'Over four seasons, the Byrde House has been the scene of some pivotal moments in Ozark. Watch as cast and crew reminisce ...', 'https://i.ytimg.com/vi/lzCoH0qXHvQ/mqdefault.jpg', 'Netflix'),
(97, 'https://www.youtube.com/watch?v=S0z3moH4570', 'Our Great National Parks | Final Trailer | Netflix | #WildForAll', 'An epic five-part series narrated by Barack Obama that invites viewers to celebrate and discover the power of our planet\'s greatest ...', 'https://i.ytimg.com/vi/S0z3moH4570/mqdefault.jpg', 'Netflix'),
(98, 'https://www.youtube.com/watch?v=FrK4xPy4ahg', 'Heartstopper | Official Trailer | Netflix', 'Love meets doubt. Fear meets joy. Boy meets boy. HEARTSTOPPER, an eight chapter story about life, love and everything in ...', 'https://i.ytimg.com/vi/FrK4xPy4ahg/mqdefault.jpg', 'Netflix'),
(99, 'https://www.youtube.com/watch?v=Ro9JbgbQHPM', 'Savage Beauty | Official Trailer | Netflix', 'Some secrets run deeper than scars. Introducing Rosemary Zimu, Savage Beauty premieres May 12, only on Netflix.', 'https://i.ytimg.com/vi/Ro9JbgbQHPM/mqdefault.jpg', 'Netflix'),
(100, 'https://www.youtube.com/watch?v=HCtDkpe89aY', 'SENIOR YEAR starring Rebel Wilson | Official Trailer | Netflix', 'After a cheerleader (Rebel Wilson) falls off a pyramid and into a 20 year coma, she wakes up as a 37-year-old woman, ready to ...', 'https://i.ytimg.com/vi/HCtDkpe89aY/mqdefault.jpg', 'Netflix'),
(101, 'https://www.youtube.com/watch?v=r6tH55syq0o', 'How programmers flex on each other', 'Top 10 ways developers flex on each other. Learn how to show off your achievements in the world of programming.', 'https://i.ytimg.com/vi/r6tH55syq0o/mqdefault.jpg', 'Fireship'),
(102, 'https://www.youtube.com/watch?v=kxT8-C1vmd4', 'Zig in 100 Seconds', 'Zig is general-purpose systems programming language often used as an alternative to C, C++, and Rust. Learn the basics of Zig ...', 'https://i.ytimg.com/vi/kxT8-C1vmd4/mqdefault.jpg', 'Fireship'),
(103, 'https://www.youtube.com/watch?v=BPadRwJbylY', '&quot;World-changing&quot; LK-99 Superconductor explained quickly', 'What is a superconductor? LK-99 claims to be the first room-temperature superconductor, and if true, it could revolutionize the ...', 'https://i.ytimg.com/vi/BPadRwJbylY/mqdefault.jpg', 'Fireship'),
(104, 'https://www.youtube.com/watch?v=cXlxMP9PU8I', 'The shocking decline of Stack Overflow', 'Stack Overflow just launched a new AI tool called Overflow AI. However, traffic to the website has already declined significantly ...', 'https://i.ytimg.com/vi/cXlxMP9PU8I/mqdefault.jpg', 'Fireship'),
(105, 'https://www.youtube.com/watch?v=n2Fluyr3lbc', 'PostgreSQL in 100 Seconds', 'Try Postgres with Neon https://bit.ly/neon-fireship right now. Postgres is one of the most popular open-source SQL databases.', 'https://i.ytimg.com/vi/n2Fluyr3lbc/mqdefault.jpg', 'Fireship'),
(106, 'https://www.youtube.com/watch?v=AE3iXR1JFak', 'Twitter rebrands to X in latest 5D chess move', 'In a surprising move, Twitter has rebranded to X and removed the bird logo. Let\'s look at recent developments with Twitter and ...', 'https://i.ytimg.com/vi/AE3iXR1JFak/mqdefault.jpg', 'Fireship'),
(107, 'https://www.youtube.com/watch?v=DXWwCggFROk', 'Is AI really getting dumber? Llama2 vs GPT-4', 'Meta just released the world\'s most powerful open-source LLM...Llama2. Let\'s see how it stacks open to OpenAI\'s GPT-4 and ...', 'https://i.ytimg.com/vi/DXWwCggFROk/mqdefault.jpg', 'Fireship'),
(108, 'https://www.youtube.com/watch?v=H1eEFfAkIik', 'SvelteKit in 100 seconds', 'Learn the basics of the SvelteKit - a metaframework that can fetch data and render Svelte web applications on the server. Find out ...', 'https://i.ytimg.com/vi/H1eEFfAkIik/mqdefault.jpg', 'Fireship'),
(109, 'https://www.youtube.com/watch?v=-Bdb2KOb_zI', 'The future of &quot;truth&quot; on the Internet', 'Let\'s take a look at the Coalition for Content Provenance and Authenticity or C2PA and its mission to curb disinformation.', 'https://i.ytimg.com/vi/-Bdb2KOb_zI/mqdefault.jpg', 'Fireship'),
(110, 'https://www.youtube.com/watch?v=p6Yw0Bx5dbw', 'ChatGPT just leveled up big time...', 'ChatGPT released the Code Interpreter plugin, making it possible for the LLM to run and test its own Python code. Learn how ...', 'https://i.ytimg.com/vi/p6Yw0Bx5dbw/mqdefault.jpg', 'Fireship'),
(111, 'https://www.youtube.com/watch?v=r-GSGH2RxJs', 'htmx in 100 seconds', 'Learn the basics of htmx - an HTML-focused UI library that can handle data fetching and rendering in web applications without ...', 'https://i.ytimg.com/vi/r-GSGH2RxJs/mqdefault.jpg', 'Fireship'),
(112, 'https://www.youtube.com/watch?v=3AS5x05XIyg', 'The sad truth about Twitterâ€™s rate limit', 'Why did Twitter recently impose a rate limit for all users? The official reason is to combat web scrapers and bots, but others have ...', 'https://i.ytimg.com/vi/3AS5x05XIyg/mqdefault.jpg', 'Fireship'),
(113, 'https://www.youtube.com/watch?v=M_wZpSEvOkc', 'This unicorn startup faked 95% of its users', 'Learn how the billion dollar startup IRL faked millions of users to raise money from venture capitalists. This scam is not is an ...', 'https://i.ytimg.com/vi/M_wZpSEvOkc/mqdefault.jpg', 'Fireship'),
(114, 'https://www.youtube.com/watch?v=3Ay6qZ88boI', 'PHP will make you poor? StackOverflow 2023 Results', 'Let\'s breakdown the StackOverflow survey results to determine the best and worst programming languages of 2023. Find out ...', 'https://i.ytimg.com/vi/3Ay6qZ88boI/mqdefault.jpg', 'Fireship'),
(115, 'https://www.youtube.com/watch?v=JY_d0vf-rfw', 'SST in 100 seconds', 'SST serverless stack is an open-source infrastructure-as-code tool for building on AWS with TypeScript. Learn how to easily ...', 'https://i.ytimg.com/vi/JY_d0vf-rfw/mqdefault.jpg', 'Fireship'),
(116, 'https://www.youtube.com/watch?v=1GSq7Je32iw', 'RIP Google Domainsâ€¦ and 5 big tech stories this week', 'Google announced it\'s selling its domain registration platform to Squarespace. In this video, we look at the 5 biggest tech stories ...', 'https://i.ytimg.com/vi/1GSq7Je32iw/mqdefault.jpg', 'Fireship'),
(117, 'https://www.youtube.com/watch?v=dCxSsr5xuL8', 'Nuxt in 100 Seconds', 'Nuxt is a full-stack JavaScript framework based on Vue.js that provides server-side rendering, data fetching, state management, ...', 'https://i.ytimg.com/vi/dCxSsr5xuL8/mqdefault.jpg', 'Fireship'),
(118, 'https://www.youtube.com/watch?v=Ch6zNEq9fwM', 'Redditâ€™s API rug pull', 'Today over 7000 subreddits have gone private in protest of the new controversial pricing of Reddit\'s API. Learn how big tech ...', 'https://i.ytimg.com/vi/Ch6zNEq9fwM/mqdefault.jpg', 'Fireship'),
(119, 'https://www.youtube.com/watch?v=VkezQMb1DHw', 'High-school student makes React a million times faster', 'Million.js is a React library that can improve rendering performance by bypassing the virtual DOM. It is inspired by blockdom and ...', 'https://i.ytimg.com/vi/VkezQMb1DHw/mqdefault.jpg', 'Fireship'),
(120, 'https://www.youtube.com/watch?v=Uc6lM1Aig9c', 'Apple makes risky bet on VR/AR future', 'The Apple Vision Pro VR headset was announced at WWDC yesterday. Let\'s take a first look its core features and how developers ...', 'https://i.ytimg.com/vi/Uc6lM1Aig9c/mqdefault.jpg', 'Fireship'),
(121, 'https://www.youtube.com/watch?v=Ibjm2KHfymo', 'Java is mounting a huge comeback', 'Java 21 will bring major improvements to the world\'s most popular enterprise programming language. Learn about unnamed ...', 'https://i.ytimg.com/vi/Ibjm2KHfymo/mqdefault.jpg', 'Fireship'),
(122, 'https://www.youtube.com/watch?v=q1fsBWLpYW4', '21 Awesome Web Features youâ€™re not using yet', 'A breakdown of the most useful new features for web developers using HTML, CSS, and JavaScript. Learn about native dialog ...', 'https://i.ytimg.com/vi/q1fsBWLpYW4/mqdefault.jpg', 'Fireship'),
(123, 'https://www.youtube.com/watch?v=V4qrvoFodmo', 'Worldcoinâ€¦ the sh*tcoin for humanity just launched', 'Worldcoin is a cryptocurrency that uses biometric iris data to verify people before making financial transactions. It is a controversial ...', 'https://i.ytimg.com/vi/V4qrvoFodmo/mqdefault.jpg', 'Fireship'),
(124, 'https://www.youtube.com/watch?v=0xnuhmqRvVQ', 'Yo mama so FAT32...', 'Learn about the major files systems used on computers like Windows, Mac, and Linux. FAT32 vs exFAT vs NTFS vs APFS vs ...', 'https://i.ytimg.com/vi/0xnuhmqRvVQ/mqdefault.jpg', 'Fireship'),
(125, 'https://www.youtube.com/watch?v=4_MDP6TcHwU', 'Why did my side-hustle fail? How to validate business ideas', 'Last week I launched a side-hustle business with voice cloning AI, but things are not going well. Learn why most business ideas ...', 'https://i.ytimg.com/vi/4_MDP6TcHwU/mqdefault.jpg', 'Fireship'),
(126, 'https://www.youtube.com/watch?v=A4_TFHzqAAg', 'How to get rich as a solo software developer - The Ultimate Guide', 'When you learn how to code, you unlock the ability to build side-businesses that have the potential to make you rich. The 6-step ...', 'https://i.ytimg.com/vi/A4_TFHzqAAg/mqdefault.jpg', 'Fireship'),
(127, 'https://www.youtube.com/watch?v=CDokUdux0rc', 'AI regulation is coming...', 'AI leaders met with U.S congress yesterday to discuss the risks that artificial intelligence pose to society and recommended that ...', 'https://i.ytimg.com/vi/CDokUdux0rc/mqdefault.jpg', 'Fireship'),
(128, 'https://www.youtube.com/watch?v=nmfRDRNjCnM', '10 crazy announcements from Google I/O', 'Google made a ton of exciting announcements at I/O yesterday related to AI, web development, Android, Flutter, and more.', 'https://i.ytimg.com/vi/nmfRDRNjCnM/mqdefault.jpg', 'Fireship'),
(129, 'https://www.youtube.com/watch?v=0rIvB3LZiKA', 'I built a smarter smart home', 'Learn how to setup a private smart home from scratch with Home Assistant and a Raspberry Pi. Add the OpenAI integration to give ...', 'https://i.ytimg.com/vi/0rIvB3LZiKA/mqdefault.jpg', 'Fireship'),
(130, 'https://www.youtube.com/watch?v=H1sXIUbpRCU', 'A Day in the Life of a Proompt Engineer', 'What is it like to be an prompt engineer? A glimpse into the life of future software developer who leverages the latest ...', 'https://i.ytimg.com/vi/H1sXIUbpRCU/mqdefault.jpg', 'Fireship'),
(131, 'https://www.youtube.com/watch?v=qQk94CjRvIs', 'Serverless was a big mistake... says Amazon', 'Amazon Prime Video released an article explaining how they saved 90% on cloud computing costs by switching from ...', 'https://i.ytimg.com/vi/qQk94CjRvIs/mqdefault.jpg', 'Fireship'),
(132, 'https://www.youtube.com/watch?v=V4gGJ7XXlC0', 'Mojo Langâ€¦ a fast futuristic Python alternative', 'Mojo is a new LLVM programming language designed as a superset of Python with the low-level performance of C. It is optimized ...', 'https://i.ytimg.com/vi/V4gGJ7XXlC0/mqdefault.jpg', 'Fireship'),
(133, 'https://www.youtube.com/watch?v=PR_ykicOZYU', 'The first casualties of AI', 'Artificial intelligence has started to make a real impact on the world by replacing human jobs and making some business models ...', 'https://i.ytimg.com/vi/PR_ykicOZYU/mqdefault.jpg', 'Fireship'),
(134, 'https://www.youtube.com/watch?v=Km0aNxhVuC4', 'Vercel dropped a database and leaked new Next.js features', 'Vercel just introduced 4 new storage products, including a serverless Postgres database, a durable Redis store, and file uploads ...', 'https://i.ytimg.com/vi/Km0aNxhVuC4/mqdefault.jpg', 'Fireship'),
(135, 'https://www.youtube.com/watch?v=bOCHTHkBoAs', '10 Math Concepts for Programmers', 'Learn 10 essential math concepts for software engineering and technical interviews. Understand how programmers use ...', 'https://i.ytimg.com/vi/bOCHTHkBoAs/mqdefault.jpg', 'Fireship'),
(136, 'https://www.youtube.com/watch?v=tszI9GrH1u0', 'I built a react appâ€¦ but with a visual editor', 'Codux is a visual IDE for React.js. Let\'s review this tool by building a simple app and find out how it can increase web ...', 'https://i.ytimg.com/vi/tszI9GrH1u0/mqdefault.jpg', 'Fireship'),
(137, 'https://www.youtube.com/watch?v=91IPJ6LFmto', 'Uh ohâ€¦ AI-search engine for developers has emerged', 'A new AI-powered search engine for developers just dropped. Unlike ChatGPT, it pulls the latest information from the web to ...', 'https://i.ytimg.com/vi/91IPJ6LFmto/mqdefault.jpg', 'Fireship'),
(138, 'https://www.youtube.com/watch?v=nQ2A30cD3Q8', 'Angular is back with a vengeance', 'Angular is adding a new feature called signals that will give it a reactive primitive similar to Vue.js and Solid. Learn how it ...', 'https://i.ytimg.com/vi/nQ2A30cD3Q8/mqdefault.jpg', 'Fireship'),
(139, 'https://www.youtube.com/watch?v=_rGXIXyNqpk', 'I built my own AutoGPT that makes videos', 'Video production is hard, so I used the latest AI technology to write, narrate, and edit videos in my own style. Everybody is ...', 'https://i.ytimg.com/vi/_rGXIXyNqpk/mqdefault.jpg', 'Fireship'),
(140, 'https://www.youtube.com/watch?v=klTvEwg3oJ4', 'Vector databases are so hot right now. WTF are they?', 'Vector databases are rapidly growing in popularity as a way to add long-term memory to LLMs like GPT-4, LLaMDA, and LLaMA.', 'https://i.ytimg.com/vi/klTvEwg3oJ4/mqdefault.jpg', 'Fireship'),
(141, 'https://www.youtube.com/watch?v=WrxnpxKarxU', 'Meet SAMâ€¦ Metaâ€™s latest AI model', 'Segment Anything Model or SAM is a new state-of-the-art AI computer vision model created at Meta. It can quickly outline objects ...', 'https://i.ytimg.com/vi/WrxnpxKarxU/mqdefault.jpg', 'Fireship'),
(142, 'https://www.youtube.com/watch?v=iO1mwxPNP5A', 'Masterclass: AI-driven Development for Programmers', 'AI tools like ChatGPT and GPT-4 are changing the way programmers write code. Learn how build a React app with Typescript ...', 'https://i.ytimg.com/vi/iO1mwxPNP5A/mqdefault.jpg', 'Fireship'),
(143, 'https://www.youtube.com/watch?v=GXN34w8kju4', 'Twitter algorithm open-sourcedâ€¦ Is Elon playing 5D chess?', 'Take a look inside the Twitter algorithm now that it has been released as open-source code. Why would Elon Musk would make a ...', 'https://i.ytimg.com/vi/GXN34w8kju4/mqdefault.jpg', 'Fireship'),
(144, 'https://www.youtube.com/watch?v=J1U1h_EjkPs', 'AI is giving me an unfair advantage', 'I share my secret to gaining 10x productivity with bioavailable artificial intelligence for video production, coding, writing, and more.', 'https://i.ytimg.com/vi/J1U1h_EjkPs/mqdefault.jpg', 'Fireship'),
(145, 'https://www.youtube.com/watch?v=ZzI9JE0i6Lc', 'AWS for the Haters in 100 Seconds', 'AWS is the world\'s largest cloud provider, but it is far from perfect. Let\'s take a look at the main reasons people hate Amazon Web ...', 'https://i.ytimg.com/vi/ZzI9JE0i6Lc/mqdefault.jpg', 'Fireship'),
(146, 'https://www.youtube.com/watch?v=TpZcGhYp4rw', 'Elon wants GPT-5 stopped NOWâ€¦ 5 reasons AI kinda sucks', 'Elon Musk and many other prominent AI researchers signed a petition to stop training on all models beyond GPT-4 to assess the ...', 'https://i.ytimg.com/vi/TpZcGhYp4rw/mqdefault.jpg', 'Fireship'),
(147, 'https://www.youtube.com/watch?v=xRMPKQweySE', 'Ansible in 100 Seconds', 'Ansible is an Infrastructure-as-Code tool that can automate almost any task on a Linux server. Learn how to use it manage your ...', 'https://i.ytimg.com/vi/xRMPKQweySE/mqdefault.jpg', 'Fireship'),
(148, 'https://www.youtube.com/watch?v=-HYbFm67Gs8', 'I literally connected my brain to GPT-4 with JavaScript', 'I hacked my brain with a compact electroencephalogram (EEG) and connected it to GPT-4 with the OpenAI API. In this crazy ...', 'https://i.ytimg.com/vi/-HYbFm67Gs8/mqdefault.jpg', 'Fireship'),
(149, 'https://www.youtube.com/watch?v=qLGmj86-j4k', 'Unreal Engine 5.2 is getting too real', 'Take a first look at Unreal Engine 5.2 and it\'s new substrate material framework and experimental procedural generation tools.', 'https://i.ytimg.com/vi/qLGmj86-j4k/mqdefault.jpg', 'Fireship'),
(150, 'https://www.youtube.com/watch?v=mpnh1YTT66w', 'ChatGPT gets another insane new buff', 'OpenAI just released a new ChatGPT plugin marketplace allowing businesses to integrate their own custom apps. In addition, it ...', 'https://i.ytimg.com/vi/mpnh1YTT66w/mqdefault.jpg', 'Fireship'),
(151, 'https://www.youtube.com/watch?v=q1HZj40ZQrM', 'Game overâ€¦ GitHub Copilot X announced', 'GitHub Copilot X was announced yesterday and it has an impressive set of new AI coding features. Learn how Microsoft is ...', 'https://i.ytimg.com/vi/q1HZj40ZQrM/mqdefault.jpg', 'Fireship'),
(152, 'https://www.youtube.com/watch?v=xW9DJTvB3NI', 'Google Bardâ€¦ the ChatGPT killer?', 'Google just released Bard, an generative LLM similar to ChatGPT. Let\'s take a first look at Bard and compare it to OpenAI\'s GPT-4.', 'https://i.ytimg.com/vi/xW9DJTvB3NI/mqdefault.jpg', 'Fireship'),
(153, 'https://www.youtube.com/watch?v=ORMx45xqWkA', 'PyTorch in 100 Seconds', 'PyTorch is a deep learning framework for used to build artificial intelligence software with Python. Learn how to build a basic ...', 'https://i.ytimg.com/vi/ORMx45xqWkA/mqdefault.jpg', 'Fireship'),
(154, 'https://www.youtube.com/watch?v=nYqeHIRKboM', 'Midjourney 5 must be stopped at all costs', 'A first look at Midjourney 5 - a state-of-the-art generative image model that can produce photorealistic humans. We breakdown ...', 'https://i.ytimg.com/vi/nYqeHIRKboM/mqdefault.jpg', 'Fireship'),
(155, 'https://www.youtube.com/watch?v=EunbKbPV2C0', 'GPT-4 has been unleashed', 'OpenAI announced GPT-4 yesterday and it\'s a beast. It can now handle 25K words of context, allowing it to provide more relevant ...', 'https://i.ytimg.com/vi/EunbKbPV2C0/mqdefault.jpg', 'Fireship'),
(156, 'https://www.youtube.com/watch?v=nMdwS3A6zck', 'Silicon Valley had a bank... HAD', 'How will the Silicon Valley Bank failure affect software engineers and tech startups? Find out why SVB got into trouble and what it ...', 'https://i.ytimg.com/vi/nMdwS3A6zck/mqdefault.jpg', 'Fireship'),
(157, 'https://www.youtube.com/watch?v=-J7EWBYipqI', 'the PATH var of righteousness', 'The PATH environment variable is like a map for navigating the maze that is your file system What is PATH in linux? How do I ...', 'https://i.ytimg.com/vi/-J7EWBYipqI/mqdefault.jpg', 'Fireship'),
(158, 'https://www.youtube.com/watch?v=26Mayv5JPz0', 'FFmpeg in 100 Seconds', 'FFmpeg is a legendary multimedia processing tool used to edit audio and video files programmatically. It can covert and transform ...', 'https://i.ytimg.com/vi/26Mayv5JPz0/mqdefault.jpg', 'Fireship'),
(159, 'https://www.youtube.com/watch?v=c4OyfL5o7DU', 'Neovim in 100 Seconds', 'Neovim is a fork of the keyboard-based text editor Vim. It is focused on extensibility and integrates the Lua programming language ...', 'https://i.ytimg.com/vi/c4OyfL5o7DU/mqdefault.jpg', 'Fireship'),
(160, 'https://www.youtube.com/watch?v=6V-eRPPLSy0', 'how big is a yottabyte?', 'How big is a Yottabyte? Let\'s compare the size difference of Megabytes, Gigabytes, Terabytes, Petabytes, Exabytes, Zettabytes, ...', 'https://i.ytimg.com/vi/6V-eRPPLSy0/mqdefault.jpg', 'Fireship'),
(161, 'https://www.youtube.com/watch?v=y3iLOxBTuy4', 'ChatGPT is a perfectly balanced AI with no exploits', 'A recent ChatGPT exploit known as DAN allowed users to get the AI to violate the ethics and guidelines set by OpenAI. The results ...', 'https://i.ytimg.com/vi/y3iLOxBTuy4/mqdefault.jpg', 'Fireship'),
(162, 'https://www.youtube.com/watch?v=jb2AvF8XzII', '15 futuristic databases youâ€™ve never heard of', 'Let\'s take a look at the top 15 new databases that could disrupt software development in the future. Many new serverless ...', 'https://i.ytimg.com/vi/jb2AvF8XzII/mqdefault.jpg', 'Fireship'),
(163, 'https://www.youtube.com/watch?v=2OTq15A5s0Y', '7 better ways to create a React app', 'What is the best tool for starting a new React project in 2023? Let\'s look at 7 good alternatives to create-react-app for starting a ...', 'https://i.ytimg.com/vi/2OTq15A5s0Y/mqdefault.jpg', 'Fireship'),
(164, 'https://www.youtube.com/watch?v=1LV1K69885E', 'The weird future of music', 'Google recently demonstrated how MusicLM can compose high-fidelity audio from a text prompt with generative AI technology.', 'https://i.ytimg.com/vi/1LV1K69885E/mqdefault.jpg', 'Fireship'),
(165, 'https://www.youtube.com/watch?v=DXDe-2BC4cE', 'Unreal in 100 Seconds', 'Unreal engine is a collection of developer tools for building interactive 3D games, simulations, and visualizations. It provides a ...', 'https://i.ytimg.com/vi/DXDe-2BC4cE/mqdefault.jpg', 'Fireship');
INSERT INTO `youtube_channel_videos` (`id`, `videoLink`, `title`, `description`, `thumbnail`, `channel`) VALUES
(166, 'https://www.youtube.com/watch?v=T6L9EoBy8Zk', 'Neo4j in 100 Seconds', 'Neo4j is a native graph database designed to handle highly complex relational data. Learn the basics of graph data modeling and ...', 'https://i.ytimg.com/vi/T6L9EoBy8Zk/mqdefault.jpg', 'Fireship'),
(167, 'https://www.youtube.com/watch?v=Z8omJ59hNfY', 'real eyes realize AI lies', 'My story about the future of artificial intelligence, chatGPT, MidJourney, deep fakes, generative art, brain chips, and more!', 'https://i.ytimg.com/vi/Z8omJ59hNfY/mqdefault.jpg', 'Fireship'),
(168, 'https://www.youtube.com/watch?v=Aa83vRghue4', '5 ideas for your own AI grift with ChatGPT', 'ChatGPT could start a new technological gold rush for artificial intelligence startups. Let\'s look at 5 business ideas for GPT-3 and ...', 'https://i.ytimg.com/vi/Aa83vRghue4/mqdefault.jpg', 'Fireship'),
(169, 'https://www.youtube.com/watch?v=lHZwlzOUOZ4', 'Tailwind CSS is the worstâ€¦', 'People have been debating the merits of Tailwind on twitter recently, so let\'s look at the pros and cons of this popular CSS library.', 'https://i.ytimg.com/vi/lHZwlzOUOZ4/mqdefault.jpg', 'Fireship'),
(170, 'https://www.youtube.com/watch?v=vdiYtiKD8eI', 'The Official JavaScript Tier List is Here', 'Breakdown of the State of JS survey results released in 2023. Which web frameworks are most popular and which ones are most ...', 'https://i.ytimg.com/vi/vdiYtiKD8eI/mqdefault.jpg', 'Fireship'),
(171, 'https://www.youtube.com/watch?v=uvb00oaa3k8', 'Kafka in 100 Seconds', 'Apache Kafka is a distributed event streaming platform used to handle large amounts of realtime data. Learn the basics of Kafka in ...', 'https://i.ytimg.com/vi/uvb00oaa3k8/mqdefault.jpg', 'Fireship'),
(172, 'https://www.youtube.com/watch?v=NGXW4xhlYa4', 'Reverse Engineering Logan Paul&#39;s Scam', 'Learn how Logan Paul\'s alleged scam, CryptoZoo, works under the hood on the Ethereum blockchain. Let\'s break down the ...', 'https://i.ytimg.com/vi/NGXW4xhlYa4/mqdefault.jpg', 'Fireship'),
(173, 'https://www.youtube.com/watch?v=5_t_I_4OuwQ', 'get a grip on grep', 'grep is a fundamental on GNU Linux tool finding files that contain a string or regex pattern. Learn the basics of grep in this quick ...', 'https://i.ytimg.com/vi/5_t_I_4OuwQ/mqdefault.jpg', 'Fireship'),
(174, 'https://www.youtube.com/watch?v=66tfvFeALBQ', 'How to ACTUALLY learn to code... 7 Roadmaps for 2023', 'Explore 7 roadmaps or learning paths for beginner developers. The goal of this video is to provide a starting point for aspiring ...', 'https://i.ytimg.com/vi/66tfvFeALBQ/mqdefault.jpg', 'Fireship'),
(175, 'https://www.youtube.com/watch?v=U_QNznf2FZA', 'JPG vs PNG vs WEBP vs GIF vs SVG', 'Now watch SVG in 100 Seconds https://youtu.be/emFMHH2Bfvo What is the difference between popular image formats like JPEG, ...', 'https://i.ytimg.com/vi/U_QNznf2FZA/mqdefault.jpg', 'Fireship'),
(176, 'https://www.youtube.com/watch?v=M93w3TjzVUE', 'Why my chat app brokeâ€¦ a cautionary tale', 'My chat app became overwhelmed with profanity and spam, but all this could have been avoided with better security practices.', 'https://i.ytimg.com/vi/M93w3TjzVUE/mqdefault.jpg', 'Fireship'),
(177, 'https://www.youtube.com/watch?v=K7iRfOs-aUw', 'Database Sharting Explained', 'How do large apps grow their databases to millions of users? In this quick video we explain the difference between horizontal and ...', 'https://i.ytimg.com/vi/K7iRfOs-aUw/mqdefault.jpg', 'Fireship'),
(178, 'https://www.youtube.com/watch?v=gUYBFDPZ5qk', 'I built a $5 chat app with Pocketbase &amp; Svelte. Will it scale?', 'Learn how build a fullstack realtime chat app with Svelte and Pocketbase, then deploy it to a Linux server for just $5. Let\'s find out ...', 'https://i.ytimg.com/vi/gUYBFDPZ5qk/mqdefault.jpg', 'Fireship'),
(179, 'https://www.youtube.com/watch?v=8B20fRB78nA', '7 killer website features', 'The top 7 features that will kill your website and make visitors hate you #webdevelopment #comedy #shorts.', 'https://i.ytimg.com/vi/8B20fRB78nA/mqdefault.jpg', 'Fireship'),
(180, 'https://www.youtube.com/watch?v=uEJ-Rnm2yOE', 'SvelteKit is my mistress', 'SvelteKit just hit version 1.0 and provides an awesome set of tools for building fullstack web applications. Let\'s take a first look at ...', 'https://i.ytimg.com/vi/uEJ-Rnm2yOE/mqdefault.jpg', 'Fireship'),
(181, 'https://www.youtube.com/watch?v=1ENiVwk8idM', 'Arduino in 100 Seconds', 'Arduino is a programmable circuit board that makes it possible for the average developer to build custom hardware products.', 'https://i.ytimg.com/vi/1ENiVwk8idM/mqdefault.jpg', 'Fireship'),
(182, 'https://www.youtube.com/watch?v=eaedq1Jl2fc', 'What will AI Programming look like in 5 Years?', 'What will the future of AI programming look like with tools like ChatGPT and GitHub Copilot? Let\'s take a look at how machine ...', 'https://i.ytimg.com/vi/eaedq1Jl2fc/mqdefault.jpg', 'Fireship'),
(183, 'https://www.youtube.com/watch?v=1v_TEnpqHXE', 'Things are gonna get weird in 2023', '2022 was a crazy year. Let\'s take a look at 10 tech trends and how they will affect software engineers going into the year 2023.', 'https://i.ytimg.com/vi/1v_TEnpqHXE/mqdefault.jpg', 'Fireship'),
(184, 'https://www.youtube.com/watch?v=zBZgdTb-dns', 'Supabase in 100 Seconds', 'Supabase is the open-source Firebase alternative that features an impressive collection of tools like PostgreSQL, user ...', 'https://i.ytimg.com/vi/zBZgdTb-dns/mqdefault.jpg', 'Fireship'),
(185, 'https://www.youtube.com/watch?v=aXOChLn5ZdQ', 'JavaScript for the Haters', 'Why does everybody hate JavaScript so much? A complete roast of JS that highlights the strongest criticisms against the world\'s ...', 'https://i.ytimg.com/vi/aXOChLn5ZdQ/mqdefault.jpg', 'Fireship'),
(186, 'https://www.youtube.com/watch?v=lkIFF4maKMU', '100+ JavaScript Concepts you Need to Know', 'The ultimate 10 minute JavaScript course that quickly breaks down over 100 key concepts every web developer should know.', 'https://i.ytimg.com/vi/lkIFF4maKMU/mqdefault.jpg', 'Fireship'),
(187, 'https://www.youtube.com/watch?v=DVWu2b7mvFg', 'a solid start', 'Here\'s your first look at Solid Start, a meta-framework for Solid.js that supports server-side rendering and advanced data fetching.', 'https://i.ytimg.com/vi/DVWu2b7mvFg/mqdefault.jpg', 'Fireship'),
(188, 'https://www.youtube.com/watch?v=2pfcynxODJc', 'Is FAANG f**ked?', 'Meta announced layoffs of 11000 employees today, just one week after Twitter implemented a massive layoff. How will this news ...', 'https://i.ytimg.com/vi/2pfcynxODJc/mqdefault.jpg', 'Fireship'),
(189, 'https://www.youtube.com/watch?v=WHyOHQ_GkNo', 'Nim in 100 Seconds', 'Nim is a general-purpose programming language known for its python-like syntax and ability to compile to multiple languages like ...', 'https://i.ytimg.com/vi/WHyOHQ_GkNo/mqdefault.jpg', 'Fireship'),
(190, 'https://www.youtube.com/watch?v=HleppfVh8jc', 'When your JavaScript framework gets acquired', 'The Remix React framework is joining forces with Shopify where it will be integrated into its Hydrogen framework. Interestingly ...', 'https://i.ytimg.com/vi/HleppfVh8jc/mqdefault.jpg', 'Fireship'),
(191, 'https://www.youtube.com/watch?v=_w0Ikk4JY7U', 'Next.js 13â€¦ this changes everything', 'Next.js version 13 was announced yesterday and it brings huge changes to the framework. They collaborated directly with the ...', 'https://i.ytimg.com/vi/_w0Ikk4JY7U/mqdefault.jpg', 'Fireship'),
(192, 'https://www.youtube.com/watch?v=Zs9Tifup1Bc', 'Is coding really dead? 6 trends that look bad', 'Some people say programming is a dying skill, but is this prediction accurate? Let\'s look at 6 trends in tech that don\'t look good for ...', 'https://i.ytimg.com/vi/Zs9Tifup1Bc/mqdefault.jpg', 'Fireship'),
(193, 'https://www.youtube.com/watch?v=QKgTZWbwD1U', 'Godot in 100 Seconds', 'Godot is a popular open source engine for building 2D and 3D games. It is similar to Unity in many ways, but is lightweight (35Mb) ...', 'https://i.ytimg.com/vi/QKgTZWbwD1U/mqdefault.jpg', 'Fireship'),
(194, 'https://www.youtube.com/watch?v=X3jw1JVNdPE', 'how to never write bug', 'Debugging is one of the most important skills of a software engineer. Learn 7 techniques, strategies, and tools for debugging as a ...', 'https://i.ytimg.com/vi/X3jw1JVNdPE/mqdefault.jpg', 'Fireship'),
(195, 'https://www.youtube.com/watch?v=INUHCQST7CU', 'Lisp in 100 Seconds', 'Lisp is world\'s second high-level programming language and is still used to build software today. It was the first to implement ...', 'https://i.ytimg.com/vi/INUHCQST7CU/mqdefault.jpg', 'Fireship'),
(196, 'https://www.youtube.com/watch?v=h55emgImrLk', 'Stop calling Fleet a VS Code Killer', 'Fleet has arrived... a brand new IDE from JetBrains that many have called a \"VS Code killer\". It has a feature called smart mode ...', 'https://i.ytimg.com/vi/h55emgImrLk/mqdefault.jpg', 'Fireship'),
(197, 'https://www.youtube.com/watch?v=OoQLoKHhohg', '7 Things No Programmer Ever Wants to Hear', 'What are some of the worst things about being a programmer? Let\'s look at 7 dreaded messages that a software engineer never ...', 'https://i.ytimg.com/vi/OoQLoKHhohg/mqdefault.jpg', 'Fireship'),
(198, 'https://www.youtube.com/watch?v=rIfdg_Ot-LI', 'Laravel in 100 Seconds', 'Laravel is a popular fullstack MVC framework for building web apps with PHP. Learn the fundamentals of Laravel and find out why ...', 'https://i.ytimg.com/vi/rIfdg_Ot-LI/mqdefault.jpg', 'Fireship'),
(199, 'https://www.youtube.com/watch?v=x2eF3YLiNhY', 'Qwikâ€¦ the world&#39;s first O(1) JavaScript framework?', 'Qwik is a JavaScript framework that uses a new rendering paradigm called resumability. It can serialize a JavaScript app into ...', 'https://i.ytimg.com/vi/x2eF3YLiNhY/mqdefault.jpg', 'Fireship'),
(200, 'https://www.youtube.com/watch?v=C7WFwgDRStM', 'SurrealDB in 100 Seconds', 'SurrealDB is a \"NewSQL\" multi-model database with an impressive list of features from popular relational, graph, and document ...', 'https://i.ytimg.com/vi/C7WFwgDRStM/mqdefault.jpg', 'Fireship');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `youtube_channels`
--
ALTER TABLE `youtube_channels`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `youtube_channel_videos`
--
ALTER TABLE `youtube_channel_videos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `youtube_channels`
--
ALTER TABLE `youtube_channels`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `youtube_channel_videos`
--
ALTER TABLE `youtube_channel_videos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=201;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
